[package]
name = "pretty-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
colored = "3"
clap = { version = "4.5.40", features = ["derive"] }
chrono = "0.4"
dateparser = "0.2.1"
signal-hook = { version = "0.3.18", features = ["extended-siginfo"] }

[dev-dependencies]
regex = "1.11"
